import { useState, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Link } from 'react-router-dom';
import SEOHead from '../../components/SEOHead';
import { QRCodeCanvas } from 'qrcode.react';
import {
  FaWindows, FaQrcode, FaInfinity, FaBolt,
  FaCheck, FaDownload, FaLink, FaFont,
  FaWifi, FaEnvelope, FaPalette, FaShieldAlt, FaRegCopy,
} from 'react-icons/fa';
import './NishanProduct.css';

/* ── Design tokens ── */
const AC = '#c8f23a';

/* ── Schemas ── */
const appSchema = {
  '@context': 'https://schema.org', '@type': 'SoftwareApplication',
  name: 'Nishan QR Code Generator',
  applicationCategory: 'UtilitiesApplication',
  operatingSystem: 'Web Browser, Windows 10, Windows 11',
  description: 'Free online QR code generator. Create unlimited, custom QR codes for URLs, text, WiFi networks, and email — with full colour control and instant PNG download. No sign-up. Also available as a Windows desktop app.',
  url: 'https://minderfly.com/store/nishan-qr-generator',
  downloadUrl: 'https://apps.microsoft.com/store/detail/nishan-qr-code-generator/9NBLGGH4N9W2',
  offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
  aggregateRating: { '@type': 'AggregateRating', ratingValue: '4.8', reviewCount: '187' },
  author: { '@type': 'Organization', name: 'Minderfly', url: 'https://minderfly.com' },
};
const faqSchema = {
  '@context': 'https://schema.org', '@type': 'FAQPage',
  mainEntity: [
    { '@type': 'Question', name: 'Is Nishan QR Code Generator completely free?', acceptedAnswer: { '@type': 'Answer', text: 'Yes. Nishan QR is 100% free for personal and commercial use. No watermarks, no account, no hidden fees, no usage caps.' } },
    { '@type': 'Question', name: 'Do QR codes generated here expire?', acceptedAnswer: { '@type': 'Answer', text: 'No. All codes are static — the data is embedded directly in the pattern. They work forever as long as your URL or content remains valid.' } },
    { '@type': 'Question', name: 'Is my data private and safe?', acceptedAnswer: { '@type': 'Answer', text: 'Yes. Generation happens entirely in your browser. Your QR code content is never sent to any server.' } },
    { '@type': 'Question', name: 'What download format is available?', acceptedAnswer: { '@type': 'Answer', text: 'PNG at high resolution. For SVG export, batch generation, and logo integration, the Nishan QR Windows desktop app is free to download.' } },
    { '@type': 'Question', name: 'Can I use these QR codes commercially?', acceptedAnswer: { '@type': 'Answer', text: 'Yes. All codes generated by Nishan QR are yours to use on any print, digital, or commercial material without restriction.' } },
  ],
};
const bcSchema = {
  '@context': 'https://schema.org', '@type': 'BreadcrumbList',
  itemListElement: [
    { '@type': 'ListItem', position: 1, name: 'Home',  item: 'https://minderfly.com/' },
    { '@type': 'ListItem', position: 2, name: 'Store', item: 'https://minderfly.com/store' },
    { '@type': 'ListItem', position: 3, name: 'Nishan QR Generator', item: 'https://minderfly.com/store/nishan-qr-generator' },
  ],
};

/* ── Feature list ── */
const FEATURES = [
  { Icon: FaQrcode,    title: 'Print-Quality PNG',    desc: 'High-resolution output at any configured size — sharp enough for business cards, banners, or billboard prints.' },
  { Icon: FaBolt,      title: 'Instant Generation',   desc: 'Your QR code updates in real time as you type. No page reload, no delay, no button to press.' },
  { Icon: FaInfinity,  title: 'Unlimited & Free',     desc: 'Generate as many codes as you need, every day. No account required and no usage caps — ever.' },
  { Icon: FaPalette,   title: 'Full Colour Control',  desc: 'Customise both foreground and background colours to match your brand using the live colour pickers.' },
  { Icon: FaShieldAlt, title: 'Browser-Only Privacy', desc: 'All generation runs locally in your browser. Your WiFi passwords and link data never touch a server.' },
  { Icon: FaWindows,   title: 'Windows Desktop App',  desc: 'Need SVG export, batch codes, or logo embedding? The Nishan QR Windows app is free on the Microsoft Store.' },
];

const TABS = [
  { id: 'link',  Icon: FaLink,    label: 'Link'  },
  { id: 'text',  Icon: FaFont,    label: 'Text'  },
  { id: 'wifi',  Icon: FaWifi,    label: 'WiFi'  },
  { id: 'email', Icon: FaEnvelope, label: 'Email' },
];

const tabAnim = { hidden: { opacity: 0, y: 8 }, visible: { opacity: 1, y: 0, transition: { duration: 0.22 } } };

/* ════════════════════════════════════════
   COMPONENT
════════════════════════════════════════ */
const NishanQr = () => {
  const [activeTab, setActiveTab] = useState('link');
  const [qrValue,   setQrValue]   = useState('https://minderfly.com');
  const [config,    setConfig]    = useState({ bgColor: '#ffffff', fgColor: '#000000', size: 280, margin: true, level: 'H' });
  const [wifi,  setWifi]  = useState({ ssid: '', password: '', encryption: 'WPA' });
  const [email, setEmail] = useState({ email: '', subject: '', body: '' });
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    if (activeTab === 'wifi') {
      setQrValue(`WIFI:T:${wifi.encryption};S:${wifi.ssid};P:${wifi.password};;`);
    } else if (activeTab === 'email') {
      setQrValue(`mailto:${email.email}?subject=${encodeURIComponent(email.subject)}&body=${encodeURIComponent(email.body)}`);
    }
  }, [activeTab, wifi, email]);

  const handleSimple = (e) => setQrValue(e.target.value);

  const downloadQR = () => {
    const canvas = document.querySelector('#qr-gen canvas');
    if (!canvas) return;
    const a = document.createElement('a');
    a.href     = canvas.toDataURL('image/png').replace('image/png', 'image/octet-stream');
    a.download = `nishan-qr-${activeTab}.png`;
    document.body.appendChild(a); a.click(); document.body.removeChild(a);
  };

  const copyContent = async () => {
    try { await navigator.clipboard.writeText(qrValue); setCopied(true); setTimeout(() => setCopied(false), 2000); } catch {}
  };

  const MS_URL = 'https://apps.microsoft.com/store/detail/nishan-qr-code-generator/9NBLGGH4N9W2';

  return (
    <>
      <SEOHead
        title="Nishan QR Code Generator | Free Online Tool | Minderfly Store"
        description="Free online QR code generator. Create unlimited, custom QR codes for URLs, text, WiFi networks, and email — with full colour control and instant PNG download. No sign-up."
        keywords="qr code generator, free online qr generator, custom qr code, wifi qr code, email qr code, nishan qr, minderfly store"
        canonical="https://minderfly.com/store/nishan-qr-generator"
        ogType="website"
        schema={[appSchema, faqSchema, bcSchema]}
      />

      <div className="nishan-wrapper">

        {/* ── NAV ── */}
        <nav className="nishan-nav" aria-label="Product navigation">
          <div className="nishan-container nav-container">
            <Link to="/store" className="nishan-back-link">← Store</Link>
            <div className="nishan-logo">Nishan&nbsp;<span className="nishan-accent">QR</span></div>
            <a href={MS_URL} target="_blank" rel="noopener noreferrer" className="btn-nishan-sm">
              <FaWindows /> Windows App
            </a>
          </div>
        </nav>

        {/* ── PAGE HERO STRIP ── */}
        <div className="nishan-hero-strip" style={{ paddingTop: 64 }}>
          <div className="nishan-container" style={{ padding: '52px 3rem 0' }}>
            {/* Breadcrumb */}
            <nav aria-label="Breadcrumb" style={{ display:'flex', alignItems:'center', gap:8, fontSize:'.75rem', color:'rgba(255,255,255,.28)', marginBottom:'1.75rem' }}>
              <Link to="/"     style={{ color:'rgba(255,255,255,.32)', textDecoration:'none' }}>Home</Link>
              <span aria-hidden="true">›</span>
              <Link to="/store" style={{ color:'rgba(255,255,255,.32)', textDecoration:'none' }}>Store</Link>
              <span aria-hidden="true">›</span>
              <span aria-current="page" style={{ color:'rgba(255,255,255,.55)' }}>Nishan QR Generator</span>
            </nav>

            {/* Accent line */}
            <div style={{ display:'inline-flex', alignItems:'center', gap:10, fontSize:'.62rem', fontWeight:700, letterSpacing:'.2em', textTransform:'uppercase', color:AC, marginBottom:'1rem' }}>
              <span style={{ width:20, height:1, background:AC, display:'block' }}/>
              Free Online Tool · No Sign-Up
            </div>

            <motion.div initial={{ opacity:0, y:18 }} animate={{ opacity:1, y:0 }} transition={{ duration:.7, ease:[.22,1,.36,1] }}
              style={{ maxWidth:660, paddingBottom:'3.5rem' }}>
              <h1 style={{ fontFamily:'var(--font-heading)', fontSize:'clamp(2.2rem,4.5vw,3.6rem)', fontWeight:800, lineHeight:.94, letterSpacing:'-.045em', color:'#fff', marginBottom:'1rem' }}>
                Free QR Code<br/>
                <span style={{ WebkitTextStroke:'1.5px rgba(255,255,255,.18)', color:'transparent' }}>Generator Online</span>
              </h1>
              <p style={{ fontSize:'1rem', fontWeight:300, color:'rgba(255,255,255,.42)', lineHeight:1.68, maxWidth:540, marginBottom:'1.75rem' }}>
                Create unlimited QR codes for URLs, WiFi, text, and email in seconds — with custom colours and instant PNG download. No account, no watermarks, works entirely in your browser.
              </p>
              {/* Trust pills */}
              <div style={{ display:'flex', flexWrap:'wrap', gap:8 }}>
                {['★ 4.8 rated','5,000+ users','100% free','No sign-up','Static codes — never expire'].map(t => (
                  <span key={t} style={{ padding:'4px 12px', borderRadius:100, background:'rgba(255,255,255,.05)', border:'1px solid rgba(255,255,255,.09)', fontSize:'.7rem', color:'rgba(255,255,255,.5)', letterSpacing:'.03em' }}>{t}</span>
                ))}
              </div>
            </motion.div>
          </div>
        </div>

        {/* ── WORKSPACE ── */}
        <main className="nishan-main-workspace" aria-label="QR code generator">
          <div className="nishan-container workspace-grid">

            {/* LEFT: Controls */}
            <motion.div initial={{ opacity:0, x:-22 }} animate={{ opacity:1, x:0 }} transition={{ duration:.65, ease:[.22,1,.36,1] }}>
              <div className="controls-header">
                <h2>Create your <span className="gradient-text">Custom QR</span></h2>
                <p>Choose a type, enter your content, and customise the colours.</p>
              </div>

              {/* Tabs */}
              <div className="qr-type-tabs" role="tablist" aria-label="QR code type">
                {TABS.map(({ id, Icon, label }) => (
                  <button key={id} role="tab" aria-selected={activeTab === id}
                    className={`tab-btn${activeTab === id ? ' active' : ''}`}
                    onClick={() => setActiveTab(id)}>
                    <Icon aria-hidden="true" /> {label}
                  </button>
                ))}
              </div>

              {/* Input areas */}
              <div className="input-area" role="tabpanel">
                <AnimatePresence mode="wait">
                  {activeTab === 'link' && (
                    <motion.div key="link" variants={tabAnim} initial="hidden" animate="visible" exit="hidden" className="input-group">
                      <label htmlFor="qr-url">Website URL</label>
                      <input id="qr-url" type="url" placeholder="https://example.com" value={qrValue} onChange={handleSimple} className="nishan-input" aria-label="URL for QR code" autoComplete="off" />
                    </motion.div>
                  )}
                  {activeTab === 'text' && (
                    <motion.div key="text" variants={tabAnim} initial="hidden" animate="visible" exit="hidden" className="input-group">
                      <label htmlFor="qr-text">Plain Text</label>
                      <textarea id="qr-text" rows={4} placeholder="Enter your text here…" value={qrValue} onChange={handleSimple} className="nishan-input" aria-label="Text for QR code" />
                    </motion.div>
                  )}
                  {activeTab === 'wifi' && (
                    <motion.div key="wifi" variants={tabAnim} initial="hidden" animate="visible" exit="hidden" className="input-stack">
                      <div className="input-group">
                        <label htmlFor="wifi-ssid">Network Name (SSID)</label>
                        <input id="wifi-ssid" type="text" placeholder="MyWiFi" value={wifi.ssid} onChange={e => setWifi({ ...wifi, ssid: e.target.value })} className="nishan-input" />
                      </div>
                      <div className="input-group">
                        <label htmlFor="wifi-pw">Password</label>
                        <input id="wifi-pw" type="text" placeholder="Leave blank for open networks" value={wifi.password} onChange={e => setWifi({ ...wifi, password: e.target.value })} className="nishan-input" />
                      </div>
                      <div className="input-group">
                        <label htmlFor="wifi-enc">Encryption</label>
                        <select id="wifi-enc" value={wifi.encryption} onChange={e => setWifi({ ...wifi, encryption: e.target.value })} className="nishan-input">
                          <option value="WPA">WPA / WPA2 (recommended)</option>
                          <option value="WEP">WEP (legacy)</option>
                          <option value="nopass">None — open network</option>
                        </select>
                      </div>
                    </motion.div>
                  )}
                  {activeTab === 'email' && (
                    <motion.div key="email" variants={tabAnim} initial="hidden" animate="visible" exit="hidden" className="input-stack">
                      <div className="input-group">
                        <label htmlFor="em-addr">Email Address</label>
                        <input id="em-addr" type="email" placeholder="user@example.com" value={email.email} onChange={e => setEmail({ ...email, email: e.target.value })} className="nishan-input" />
                      </div>
                      <div className="input-group">
                        <label htmlFor="em-sub">Subject (optional)</label>
                        <input id="em-sub" type="text" placeholder="Inquiry…" value={email.subject} onChange={e => setEmail({ ...email, subject: e.target.value })} className="nishan-input" />
                      </div>
                      <div className="input-group">
                        <label htmlFor="em-body">Message (optional)</label>
                        <textarea id="em-body" rows={3} placeholder="Type your message…" value={email.body} onChange={e => setEmail({ ...email, body: e.target.value })} className="nishan-input" />
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>

              {/* Appearance */}
              <div className="customization-section">
                <h3><FaPalette aria-hidden="true" /> Appearance</h3>
                <div className="color-pickers">
                  <div className="color-control">
                    <label htmlFor="fg-color">Foreground</label>
                    <div className="color-wrapper">
                      <input id="fg-color" type="color" value={config.fgColor} onChange={e => setConfig({ ...config, fgColor: e.target.value })} aria-label="QR code foreground colour" />
                      <span>{config.fgColor}</span>
                    </div>
                  </div>
                  <div className="color-control">
                    <label htmlFor="bg-color">Background</label>
                    <div className="color-wrapper">
                      <input id="bg-color" type="color" value={config.bgColor} onChange={e => setConfig({ ...config, bgColor: e.target.value })} aria-label="QR code background colour" />
                      <span>{config.bgColor}</span>
                    </div>
                  </div>
                </div>
              </div>

              {/* Pro upsell */}
              <div className="pro-upsell-card">
                <div className="pro-upsell-icon"><FaWindows /></div>
                <div>
                  <strong>Need SVG export or logo embedding?</strong>
                  <p>The Nishan QR Windows desktop app adds vector SVG output, logo integration, batch generation, and higher error-correction options.</p>
                  <a href={MS_URL} target="_blank" rel="noopener noreferrer" className="pro-upsell-link">
                    <FaWindows aria-hidden="true" /> Get Windows App — Free
                  </a>
                </div>
              </div>
            </motion.div>

            {/* RIGHT: Preview */}
            <motion.div initial={{ opacity:0, x:22 }} animate={{ opacity:1, x:0 }} transition={{ duration:.65, delay:.14, ease:[.22,1,.36,1] }}>
              <div className="preview-card-sticky">
                <div className="preview-header"><h2>Live Preview</h2></div>

                <div className="qr-canvas-wrapper" id="qr-gen" aria-label="QR code preview">
                  <QRCodeCanvas
                    value={qrValue || 'https://minderfly.com'}
                    size={config.size}
                    level={config.level}
                    includeMargin={config.margin}
                    bgColor={config.bgColor}
                    fgColor={config.fgColor}
                  />
                </div>

                <div className="preview-actions">
                  <button onClick={downloadQR} className="btn-nishan-primary full-width" aria-label="Download QR code as PNG">
                    <FaDownload aria-hidden="true" /> Download PNG
                  </button>
                </div>

                {(activeTab === 'link' || activeTab === 'text') && (
                  <button onClick={copyContent} className={`btn-copy${copied ? ' copied' : ''}`} aria-label="Copy content to clipboard">
                    <FaRegCopy aria-hidden="true" /> {copied ? '✓ Copied!' : 'Copy Content'}
                  </button>
                )}

                <p className="preview-info">Static code — works forever, no server needed.</p>

                {/* Stats */}
                <div className="preview-stats">
                  {[['★ 4.8', 'Rating'], ['5k+', 'Users'], ['Free', 'Always']].map(([v, l]) => (
                    <div key={l} className="preview-stat">
                      <span className="preview-stat-val">{v}</span>
                      <span className="preview-stat-label">{l}</span>
                    </div>
                  ))}
                </div>
              </div>
            </motion.div>
          </div>
        </main>

        {/* ── FEATURES ── */}
        <div className="nishan-legacy-content">
          <section className="nishan-features" aria-label="Why use Nishan QR">
            <div className="nishan-container">
              <div className="features-header">
                <h2>Why Nishan QR?</h2>
                <p>Built for speed, privacy, and unlimited use — with zero friction.</p>
              </div>
              <div className="features-grid">
                {FEATURES.map(({ Icon, title, desc }) => (
                  <div key={title} className="feature-box">
                    <Icon className="f-icon" aria-hidden="true" />
                    <h3>{title}</h3>
                    <p>{desc}</p>
                  </div>
                ))}
              </div>
            </div>
          </section>

          {/* ── SEO article ── */}
          <section className="nishan-seo-content" aria-label="QR code guide and FAQ">
            <div className="nishan-container">
              <article className="seo-article">
                <h2>The Best Free QR Code Generator — No Account Needed</h2>
                <p>
                  Nishan QR is a free, browser-based QR code generator that creates static codes for URLs, plain text, WiFi networks, and pre-filled email drafts. All generation runs locally in your browser — nothing is transmitted to any server, making it the safest choice for sensitive content like passwords and contact details. Unlike cloud-based generators, there are no usage caps, no monthly fees, and no expiry dates on the codes you create.
                </p>
                <p>
                  For teams and professionals who need SVG export for print production, batch code generation, or QR codes with embedded logos, the Nishan QR Windows desktop app provides all of these features — also free, via the Microsoft Store.
                </p>

                <h3>What Is a QR Code and How Does It Work?</h3>
                <p>
                  A QR (Quick Response) code is a two-dimensional barcode that stores data in a matrix of black and white squares. Modern smartphone cameras decode them instantly without a dedicated app. <strong>Static QR codes</strong> — what Nishan QR generates — embed the destination data directly in the pattern and require no server. They can never expire and carry no third-party dependency. <strong>Dynamic QR codes</strong> redirect through a provider's server, enabling analytics and editable destinations but creating a risk: if the provider shuts down or raises prices, all printed codes stop working.
                </p>

                <h3>How to Create a QR Code in 4 Steps</h3>
                <ol>
                  <li><strong>Choose the type</strong> — Link, Text, WiFi, or Email using the tabs above.</li>
                  <li><strong>Enter your content</strong> — paste a URL, type a message, or fill in the WiFi or email fields.</li>
                  <li><strong>Customise colours</strong> — set foreground and background to match your brand.</li>
                  <li><strong>Download</strong> — click "Download PNG" to save a high-resolution image immediately.</li>
                </ol>

                <h3>Popular Use Cases</h3>
                <div className="seo-grid">
                  <div className="seo-card">
                    <h4>🏢 Business Cards & Print Materials</h4>
                    <p>Link to your portfolio, booking page, or LinkedIn. A QR code replaces a long URL on any printed material and never takes up extra space.</p>
                  </div>
                  <div className="seo-card">
                    <h4>📶 Guest WiFi Access</h4>
                    <p>Let guests join your network instantly by scanning a code. No password typing, no awkward sharing. Works for homes, offices, cafés, and hotels.</p>
                  </div>
                  <div className="seo-card">
                    <h4>📧 Pre-Filled Email Enquiries</h4>
                    <p>A code that opens an email draft to your address — ideal for product packaging, event materials, and support contact pages.</p>
                  </div>
                  <div className="seo-card">
                    <h4>📦 Product Packaging & Labels</h4>
                    <p>Link to setup videos, warranty registration, or reorder pages. Static codes are safe for production print runs because they will never break.</p>
                  </div>
                </div>

                <h3>Static vs Dynamic QR Codes: Which Should You Use?</h3>
                <p>
                  <strong>Static codes</strong> (generated by Nishan QR) contain the full destination directly in the pattern. They work permanently with no internet dependency and cannot be tracked or traced. Use static codes for anything going on permanent printed material. <strong>Dynamic codes</strong> redirect through a provider's short-link server. They allow you to change the destination later and provide scan analytics — but every code becomes useless if the provider disappears. For free-tier dynamic codes, that risk is especially high.
                </p>

                <h3>Frequently Asked Questions</h3>
                <div className="faq-section" itemScope itemType="https://schema.org/FAQPage">
                  {faqSchema.mainEntity.map(f => (
                    <div key={f.name} className="faq-item" itemScope itemType="https://schema.org/Question">
                      <h4 itemProp="name">{f.name}</h4>
                      <p itemScope itemType="https://schema.org/Answer" itemProp="acceptedAnswer">
                        <span itemProp="text">{f.acceptedAnswer.text}</span>
                      </p>
                    </div>
                  ))}
                </div>
              </article>
            </div>
          </section>
        </div>

        {/* ── FOOTER ── */}
        <footer className="nishan-footer" aria-label="Footer">
          <div className="nishan-container">
            <div className="nishan-footer-content">
              <div className="nishan-footer-left">
                <span className="nishan-logo-sm">Nishan QR Generator</span>
                <p>© {new Date().getFullYear()} Minderfly. All rights reserved.</p>
              </div>
              <nav className="nishan-footer-links" aria-label="Footer links">
                <Link to="/store">Store</Link>
                <Link to="/">Minderfly</Link>
                <Link to="/articles">Blog</Link>
                <a href={MS_URL} target="_blank" rel="noopener noreferrer">Windows App</a>
              </nav>
            </div>
          </div>
        </footer>

      </div>
    </>
  );
};

export default NishanQr;